from aiogram.fsm.state import State, StatesGroup

class AdminStates(StatesGroup):
	menu = State()
	department_name = State()
	department_create = State()
	diagnos_add = State()
	diagnos_create = State()
	medicine_add = State()
	procedure_add = State()
	medicine_connect = State()
	connect_add = State()
	doctor_depart = State()
	doctor_employ = State()
	doctor_delete = State()
	patient_add = State()
	frequency = State()
	history = State()
	back = State()
	start_menu = State()


class DoctorStates(StatesGroup):
	menu = State()
	add_patient = State()
	add_patient_end = State()
	patient_name = State()
	patient_depart = State()
	select_doctor = State()
	add_diag = State()
	create_history = State()
	select_diag = State()
	select_dosage = State()
	add_appointment = State()
	select_med_proc = State()
	change_appointment = State()
	remake_appointment = State()
	patient_name_close = State()
	select_diag_close = State()
	select_med_proc_close = State()
	close_history = State()
	close_entrance = State()
	process_resign = State()
	back = State()